# Generated by Django 4.0.5 on 2022-06-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_tipounidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='webpage.tipounidad'),
        ),
    ]
