# Generated by Django 4.0.5 on 2022-06-06 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_item_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='descripcion',
            field=models.TextField(default='item_prueba', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='nombre',
            field=models.TextField(default='test'),
        ),
        migrations.AlterField(
            model_name='item',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webpage.proveedor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.IntegerField(default=1),
        ),
    ]
