# Generated by Django 4.0.5 on 2022-06-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_alter_item_cantidad_alter_item_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipounidad',
            name='cssclass',
            field=models.CharField(default='in-kg', max_length=4),
        ),
    ]
