# Generated by Django 4.0.5 on 2022-06-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_tipounidad_cssclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipounidad',
            name='cssclass',
            field=models.CharField(default='in-kg', max_length=5),
        ),
    ]
