# Generated by Django 4.0.5 on 2022-06-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_proveedor_algo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='algo',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
