# Generated by Django 4.0.5 on 2023-07-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_remove_proveedor_algo_alter_proveedor_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
                ('abr', models.CharField(max_length=3)),
                ('cssclass', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='precio',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RegistroMovimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('stockbf', models.IntegerField()),
                ('stockaf', models.IntegerField()),
                ('preciobf', models.IntegerField()),
                ('precioaf', models.IntegerField()),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.item')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.tipomovimiento')),
            ],
        ),
    ]
