# Generated by Django 4.0.5 on 2023-07-07 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_venta_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cant',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
