# Generated by Django 4.0.5 on 2023-07-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_alter_detalleventa_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='sku',
            field=models.IntegerField(),
        ),
    ]
