# Generated by Django 4.0.5 on 2023-07-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_alter_alerta_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='nivel_bajo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='nivel_sobre',
            field=models.IntegerField(null=True),
        ),
    ]
